name: Translations

# **What it does**:
# **Why we have it**:
# **Who does it impact**: Docs localization

on:
  schedule:
    - cron: '20 19 * * *' # once a day at 19:20 UTC / 11:20 PST

env:
  FREEZE: ${{ secrets.FREEZE }}

jobs:
  prepare:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.FREEZE == 'true' }}
        run: |
          echo 'The repo is currently frozen! Exiting this workflow.'
          exit 1 # prevents further steps from running
      - name: Find original Pull Request
        uses: juliangruber/find-pull-request-action@afdd62ccd2d4c55f5bdb154b489b85fc4cbcb9c1
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: translations
          base: main
          author: octoglot
          state: open
      - if: ${{ steps.pr.outputs.number }}
        name: Check if already labeled
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        id: has-label
        with:
          script: |
            const { data: labels } = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr.outputs.number }}
            })
            if (labels.find(label => label.name === 'automerge')) {
              return 'ok'
            }
      - if: ${{ !steps.has-label.outputs.result }}
        name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@2e3a01bea165781841c2ebaf0a8b3202557383e2
        with:
          github-token: ${{ secrets.DOCUBOT_REPO_PAT }}
          number: ${{ steps.pr.outputs.number }}
      - if: ${{ !steps.has-label.outputs.result }}
        name: Add automerge label
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr.outputs.number }},
              labels: ['automerge']
            })
